In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import style
style.use('ggplot')
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import warnings
warnings.filterwarnings("ignore")

In [2]:
df_train = pd.read_csv('train.csv', delimiter=',')
df_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [3]:
df_train.drop(['Name', 'Ticket', 'Fare', 'Cabin', 'Embarked'], axis=1, inplace=True)
df_train.dropna(axis=0, inplace=True)
df_train.head()

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch
0            1         0       3    male  22.0      1      0
1            2         1       1  female  38.0      1      0
2            3         1       3  female  26.0      0      0
3            4         1       1  female  35.0      1      0
4            5         0       3    male  35.0      0      0

In [4]:
df_train = pd.get_dummies(df_train, columns=['Sex'])
df_train.head()

PassengerId  Survived  Pclass   Age  SibSp  Parch  Sex_female  Sex_male
0            1         0       3  22.0      1      0           0         1
1            2         1       1  38.0      1      0           1         0
2            3         1       3  26.0      0      0           1         0
3            4         1       1  35.0      1      0           1         0
4            5         0       3  35.0      0      0           0         1

In [5]:
X = df_train.iloc[:, 2:]
y = df_train.iloc[:, 1]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
X_test

Pclass    Age  SibSp  Parch  Sex_female  Sex_male
423       3  28.00      1      1           1         0
177       1  50.00      0      0           1         0
305       1   0.92      1      2           0         1
292       2  36.00      0      0           0         1
889       1  26.00      0      0           0         1
..      ...    ...    ...    ...         ...       ...
352       3  15.00      1      1           0         1
99        2  34.00      1      0           0         1
689       1  15.00      0      1           1         0
858       3  24.00      0      3           1         0
137       1  37.00      1      0           0         1

[179 rows x 6 columns]

In [6]:
## Feature Scaling 
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [7]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)


GaussianNB(priors=None, var_smoothing=1e-09)

In [8]:
y_pred = classifier.predict(X_test)
pred_df = pd.DataFrame({
    'y_test': y_test,
    'y_pred': y_pred
})
pred_df

y_test  y_pred
423       0       1
177       0       1
305       1       0
292       0       0
889       1       0
..      ...     ...
352       0       0
99        0       0
689       1       1
858       1       1
137       0       0

[179 rows x 2 columns]

In [9]:
score = accuracy_score(y_test, y_pred)
score

0.776536312849162

In [10]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[87, 16],
       [24, 52]])

In [11]:
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.78      0.84      0.81       103
           1       0.76      0.68      0.72        76

    accuracy                           0.78       179
   macro avg       0.77      0.76      0.77       179
weighted avg       0.78      0.78      0.77       179



In [12]:
df_test = pd.read_csv('test.csv', delimiter=',')
df_test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [13]:
df_test.drop(['Name', 'Ticket', 'Fare', 'Cabin', 'Embarked'], axis=1, inplace=True)
df_test.dropna(axis=0, inplace=True)
df_test = pd.get_dummies(df_test, columns=['Sex'])
df_test.head()

PassengerId  Pclass   Age  SibSp  Parch  Sex_female  Sex_male
0          892       3  34.5      0      0           0         1
1          893       3  47.0      1      0           1         0
2          894       2  62.0      0      0           0         1
3          895       3  27.0      0      0           0         1
4          896       3  22.0      1      1           1         0

In [14]:
X_test

array([[ 0.89707924, -0.11705424,  0.515219  ,  0.65287483,  1.33117269,
        -1.33117269],
       [-1.51466646,  1.4030636 , -0.54088125, -0.49609896,  1.33117269,
        -1.33117269],
       [-1.51466646, -1.9881811 ,  0.515219  ,  1.80184861, -0.75121734,
         0.75121734],
       ...,
       [-1.51466646, -1.01530569, -0.54088125,  0.65287483,  1.33117269,
        -1.33117269],
       [ 0.89707924, -0.3934393 , -0.54088125,  2.9508224 ,  1.33117269,
        -1.33117269],
       [-1.51466646,  0.50481215,  0.515219  , -0.49609896, -0.75121734,
         0.75121734]])

In [15]:
df_test.head()
df_test_passenger_id = df_test.iloc[:, 0]
df_test = df_test.iloc[:, 1:]
df_test.head()

Pclass   Age  SibSp  Parch  Sex_female  Sex_male
0       3  34.5      0      0           0         1
1       3  47.0      1      0           1         0
2       2  62.0      0      0           0         1
3       3  27.0      0      0           0         1
4       3  22.0      1      1           1         0

In [16]:
df_test = sc.transform(df_test)
df_test

array([[ 0.89707924,  0.33207148, -0.54088125, -0.49609896, -0.75121734,
         0.75121734],
       [ 0.89707924,  1.1957748 ,  0.515219  , -0.49609896,  1.33117269,
        -1.33117269],
       [-0.30879361,  2.23221878, -0.54088125, -0.49609896, -0.75121734,
         0.75121734],
       ...,
       [ 0.89707924, -0.11705424, -0.54088125, -0.49609896,  1.33117269,
        -1.33117269],
       [-1.51466646,  0.64300468, -0.54088125, -0.49609896,  1.33117269,
        -1.33117269],
       [ 0.89707924,  0.60845655, -0.54088125, -0.49609896, -0.75121734,
         0.75121734]])

In [17]:
test_prediction = classifier.predict(df_test)
prediction_df = pd.DataFrame({
    'passenger_id': df_test_passenger_id,
    'Survived': test_prediction
})
prediction_df

passenger_id  Survived
0             892         0
1             893         1
2             894         0
3             895         0
4             896         1
..            ...       ...
409          1301         1
411          1303         1
412          1304         1
414          1306         1
415          1307         0

[332 rows x 2 columns]

In [18]:
prediction_df.to_csv('predictions.csv', sep=',')