In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import style
style.use('ggplot')
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import warnings
warnings.filterwarnings("ignore")

In [2]:
df_train = pd.read_csv('train.csv', delimiter=',')
df_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [3]:
df_train.drop(['Name', 'Ticket', 'Fare', 'Cabin', 'Embarked'], axis=1, inplace=True)
df_train.fillna(0, inplace=True)
df_train.head()

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch
0            1         0       3    male  22.0      1      0
1            2         1       1  female  38.0      1      0
2            3         1       3  female  26.0      0      0
3            4         1       1  female  35.0      1      0
4            5         0       3    male  35.0      0      0

In [4]:
df_train = pd.get_dummies(df_train, columns=['Sex'])
df_train.head()

PassengerId  Survived  Pclass   Age  SibSp  Parch  Sex_female  Sex_male
0            1         0       3  22.0      1      0           0         1
1            2         1       1  38.0      1      0           1         0
2            3         1       3  26.0      0      0           1         0
3            4         1       1  35.0      1      0           1         0
4            5         0       3  35.0      0      0           0         1

In [5]:
X = df_train.iloc[:, 2:]
y = df_train.iloc[:, 1]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
X_test

Pclass   Age  SibSp  Parch  Sex_female  Sex_male
495       3   0.0      0      0           0         1
648       3   0.0      0      0           0         1
278       3   7.0      4      1           0         1
31        1   0.0      1      0           1         0
255       3  29.0      0      2           1         0
..      ...   ...    ...    ...         ...       ...
167       3  45.0      1      4           1         0
306       1   0.0      0      0           1         0
379       3  19.0      0      0           0         1
742       1  21.0      2      2           1         0
10        3   4.0      1      1           1         0

[223 rows x 6 columns]

In [6]:
## Feature Scaling 
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [7]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state= 0)
classifier.fit(X_train, y_train)


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [8]:
y_pred = classifier.predict(X_test)
pred_df = pd.DataFrame({
    'y_test': y_test,
    'y_pred': y_pred
})
pred_df

y_test  y_pred
495       0       0
648       0       0
278       0       0
31        1       1
255       1       1
..      ...     ...
167       0       0
306       1       1
379       0       0
742       1       1
10        1       1

[223 rows x 2 columns]

In [9]:
score = accuracy_score(y_test, y_pred)
score

0.8026905829596412

In [10]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[120,  19],
       [ 25,  59]])

In [11]:
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.83      0.86      0.85       139
           1       0.76      0.70      0.73        84

    accuracy                           0.80       223
   macro avg       0.79      0.78      0.79       223
weighted avg       0.80      0.80      0.80       223



In [12]:
df_test = pd.read_csv('test.csv', delimiter=',')
df_test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [13]:
df_test.drop(['Name', 'Ticket', 'Fare', 'Cabin', 'Embarked'], axis=1, inplace=True)
df_test.fillna(0, inplace=True)
df_test = pd.get_dummies(df_test, columns=['Sex'])
df_test.head()

PassengerId  Pclass   Age  SibSp  Parch  Sex_female  Sex_male
0          892       3  34.5      0      0           0         1
1          893       3  47.0      1      0           1         0
2          894       2  62.0      0      0           0         1
3          895       3  27.0      0      0           0         1
4          896       3  22.0      1      1           1         0

In [14]:
X_test

array([[ 0.83012938, -1.35931208, -0.46037161, -0.47720996, -0.72705166,
         0.72705166],
       [ 0.83012938, -1.35931208, -0.46037161, -0.47720996, -0.72705166,
         0.72705166],
       [ 0.83012938, -0.96196621,  2.98532288,  0.73949329, -0.72705166,
         0.72705166],
       ...,
       [ 0.83012938, -0.28080185, -0.46037161, -0.47720996, -0.72705166,
         0.72705166],
       [-1.56007074, -0.16727446,  1.26247564,  1.95619654,  1.37541808,
        -1.37541808],
       [ 0.83012938, -1.1322573 ,  0.40105202,  0.73949329,  1.37541808,
        -1.37541808]])

In [15]:
df_test.head()
df_test_passenger_id = df_test.iloc[:, 0]
df_test = df_test.iloc[:, 1:]
df_test.head()

Pclass   Age  SibSp  Parch  Sex_female  Sex_male
0       3  34.5      0      0           0         1
1       3  47.0      1      0           1         0
2       2  62.0      0      0           0         1
3       3  27.0      0      0           0         1
4       3  22.0      1      1           1         0

In [16]:
df_test = sc.transform(df_test)
df_test

array([[ 0.83012938,  0.59903545, -0.46037161, -0.47720996, -0.72705166,
         0.72705166],
       [ 0.83012938,  1.30858165,  0.40105202, -0.47720996,  1.37541808,
        -1.37541808],
       [-0.36497068,  2.1600371 , -0.46037161, -0.47720996, -0.72705166,
         0.72705166],
       ...,
       [ 0.83012938,  0.82609023, -0.46037161, -0.47720996, -0.72705166,
         0.72705166],
       [ 0.83012938, -1.35931208, -0.46037161, -0.47720996, -0.72705166,
         0.72705166],
       [ 0.83012938, -1.35931208,  0.40105202,  0.73949329, -0.72705166,
         0.72705166]])

In [17]:
test_prediction = classifier.predict(df_test)
prediction_df = pd.DataFrame({
    'passenger_id': df_test_passenger_id,
    'Survived': test_prediction
})
prediction_df

passenger_id  Survived
0             892         0
1             893         0
2             894         0
3             895         1
4             896         1
..            ...       ...
413          1305         0
414          1306         1
415          1307         0
416          1308         0
417          1309         1

[418 rows x 2 columns]

In [18]:
prediction_df.to_csv('predictions.csv', sep=',')